spring:
  # 应用服务名称
  application:
    name: WebSocket
  # 指定需要加载的配置文件
  profiles:
    active: dev

# 应用服务端口号
server:
  port: 8800

webSocket:
  protocol: '/ws'
  port: 9020

# 测试连接地址：ws://127.0.0.1:9020/?userId=10000&msgContent=login
#   {"fromUserId":"10000","toUserId":"20000","msgContent":"我是第一个用户"}
#   {"fromUserId":"20000","msgContent":"我是第二个用户","toUserId":"10000"}
#   {"fromUserId":"30000","msgContent":"我是第三个用户","toUserId":"10000"}
